[build]
  command = "npm install --prefix client && npm install --prefix server && npm run build --prefix client"
  publish = "client/dist"

[functions]
  directory = "server/netlify/functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.19.0"